#include <stdbool.h>
#include <stdio.h>
#include <string.h>

#include "td2_runtime.h"

typedef struct {
    const char* label;
    const char* scene_dir;
    Td2SchedulerProfile profile;
    const char* input_script;
    unsigned frame;
    bool expect_state_0960;
    uint16_t expected_state_0960;
    bool expect_state_1c70;
    uint16_t expected_state_1c70;
    bool expect_state_1c76;
    uint16_t expected_state_1c76;
    bool expect_state_09a2;
    uint16_t expected_state_09a2;
    bool expect_state_09a8;
    uint16_t expected_state_09a8;
    bool expect_state_137c;
    uint16_t expected_state_137c;
    bool expect_dp_0020;
    uint16_t expected_dp_0020;
    bool expect_dp_0022;
    uint16_t expected_dp_0022;
    bool expect_dp_0053;
    uint16_t expected_dp_0053;
    bool expect_dp_0054;
    uint16_t expected_dp_0054;
} Td2InputMutationCase;

static const Td2InputMutationCase k_cases[] = {
    {
        "menu_no_opponent_handoff",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1584-1589:right,down;1730-1735:start",
        2044U,
        false,
        0U,
        true,
        3U,
        true,
        0U,
        false,
        0U,
        false,
        0U,
        false,
        0U,
        false,
        0U,
        false,
        0U,
        true,
        232U,
        true,
        88U,
    },
    {
        "gameplay_a_press",
        "../tools/out/design_lane3_live_race_mid_frame0_native",
        TD2_SCHEDULER_PROFILE_GAMEPLAY_LIVE_RACE_MID,
        "3:a",
        3U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        false,
        0U,
        false,
        0U,
        false,
        0U,
        false,
        0U,
        false,
        0U,
        true,
        136U,
        true,
        152U,
    },
    {
        "gameplay_b_press",
        "../tools/out/design_lane3_live_race_mid_frame0_native",
        TD2_SCHEDULER_PROFILE_GAMEPLAY_LIVE_RACE_MID,
        "5:b",
        5U,
        true,
        0x8000U,
        true,
        0U,
        true,
        1U,
        false,
        0U,
        false,
        0U,
        false,
        0U,
        false,
        0U,
        false,
        0U,
        true,
        152U,
        true,
        164U,
    },
    {
        "gameplay_diagonal_press",
        "../tools/out/design_lane3_live_race_mid_frame0_native",
        TD2_SCHEDULER_PROFILE_GAMEPLAY_LIVE_RACE_MID,
        "7:right,down",
        7U,
        true,
        0x0500U,
        true,
        0U,
        true,
        1U,
        false,
        0U,
        false,
        0U,
        false,
        0U,
        false,
        0U,
        false,
        0U,
        true,
        168U,
        true,
        176U,
    },
    {
        "gameplay_b_press_60",
        "../tools/out/design_lane3_live_race_mid_frame0_native",
        TD2_SCHEDULER_PROFILE_GAMEPLAY_LIVE_RACE_MID,
        "60:b",
        60U,
        true,
        0x8000U,
        true,
        0U,
        true,
        1U,
        true,
        43U,
        true,
        2U,
        false,
        0U,
        true,
        137U,
        true,
        0U,
        true,
        248U,
        true,
        8U,
    },
    {
        "gameplay_a_press_95",
        "../tools/out/design_lane3_live_race_mid_frame0_native",
        TD2_SCHEDULER_PROFILE_GAMEPLAY_LIVE_RACE_MID,
        "95:a",
        95U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        27U,
        true,
        10U,
        false,
        0U,
        true,
        21U,
        true,
        4U,
        true,
        224U,
        true,
        224U,
    },
    {
        "menu_default_rival_a_2052",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:a",
        2052U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        40U,
        true,
        2U,
        true,
        0U,
        true,
        89U,
        true,
        9U,
        true,
        248U,
        true,
        0U,
    },
    {
        "menu_default_rival_a_2053",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:a",
        2053U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        27U,
        true,
        2U,
        true,
        0U,
        true,
        18U,
        true,
        4U,
        true,
        0U,
        true,
        0U,
    },
    {
        "menu_default_rival_a_2054",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:a",
        2054U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        40U,
        true,
        2U,
        true,
        0U,
        true,
        88U,
        true,
        9U,
        true,
        0U,
        true,
        8U,
    },
    {
        "menu_default_rival_a_2055",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:a",
        2055U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        27U,
        true,
        2U,
        true,
        0U,
        true,
        18U,
        true,
        4U,
        true,
        8U,
        true,
        8U,
    },
    {
        "menu_default_rival_a_2062",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:a",
        2062U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        40U,
        true,
        2U,
        true,
        0U,
        true,
        82U,
        true,
        9U,
        true,
        32U,
        true,
        40U,
    },
    {
        "menu_default_rival_a_2066",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:a",
        2066U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        38U,
        true,
        2U,
        true,
        0U,
        true,
        192U,
        true,
        9U,
        true,
        48U,
        true,
        48U,
    },
    {
        "menu_default_rival_a_2068",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:a",
        2068U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        38U,
        true,
        2U,
        true,
        0U,
        true,
        83U,
        true,
        9U,
        true,
        48U,
        true,
        56U,
    },
    {
        "menu_default_rival_a_2071",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:a",
        2071U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        27U,
        true,
        2U,
        true,
        0U,
        true,
        18U,
        true,
        4U,
        true,
        64U,
        true,
        64U,
    },
    {
        "menu_default_rival_a_2082",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:a",
        2082U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        40U,
        true,
        2U,
        true,
        0U,
        true,
        89U,
        true,
        9U,
        true,
        104U,
        true,
        128U,
    },
    {
        "menu_default_rival_a_2083",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:a",
        2083U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        27U,
        true,
        2U,
        true,
        0U,
        true,
        170U,
        true,
        289U,
        true,
        128U,
        true,
        128U,
    },
    {
        "menu_default_rival_a_2084",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:a",
        2084U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        40U,
        true,
        2U,
        true,
        0U,
        true,
        89U,
        true,
        9U,
        true,
        128U,
        true,
        136U,
    },
    {
        "menu_default_rival_a_2088",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:a",
        2088U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        40U,
        true,
        2U,
        true,
        0U,
        true,
        87U,
        true,
        9U,
        true,
        144U,
        true,
        152U,
    },
    {
        "menu_default_rival_a_2104",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:a",
        2104U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        38U,
        true,
        2U,
        true,
        1U,
        true,
        105U,
        true,
        9U,
        true,
        200U,
        true,
        208U,
    },
    {
        "menu_default_rival_a_2125",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:a",
        2125U,
        true,
        0x0080U,
        true,
        0U,
        true,
        1U,
        true,
        26U,
        true,
        10U,
        true,
        1U,
        true,
        19U,
        true,
        289U,
        true,
        8U,
        true,
        8U,
    },
    {
        "menu_default_rival_b_2088",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:b",
        2088U,
        true,
        0x8000U,
        true,
        0U,
        true,
        1U,
        true,
        40U,
        true,
        2U,
        true,
        0U,
        true,
        192U,
        true,
        9U,
        true,
        8U,
        true,
        8U,
    },
    {
        "menu_default_rival_b_2125",
        "../tools/out/design_frame1500_car_select",
        TD2_SCHEDULER_PROFILE_MENU_GAMEPLAY_ENTRY,
        "1200:start;1280:start;1505-1510:start;1584-1589:right,down;1640-1645:start;1730-1735:start;2050-2208:b",
        2125U,
        true,
        0x8000U,
        true,
        0U,
        true,
        1U,
        true,
        27U,
        true,
        10U,
        true,
        0U,
        true,
        18U,
        true,
        4U,
        true,
        24U,
        true,
        24U,
    },
};

static bool expect_u16(
    const char* label,
    const char* key,
    bool actual_has_value,
    uint16_t actual_value,
    bool expected_has_value,
    uint16_t expected_value,
    unsigned* total_checks,
    unsigned* failed_checks
) {
    (*total_checks)++;
    if (actual_has_value != expected_has_value ||
        (expected_has_value && actual_value != expected_value)) {
        fprintf(stderr,
                "FAIL %s %s expected %s%u got %s%u\n",
                label,
                key,
                expected_has_value ? "" : "missing/",
                (unsigned)expected_value,
                actual_has_value ? "" : "missing/",
                (unsigned)actual_value);
        (*failed_checks)++;
        return false;
    }
    return true;
}

int main(void) {
    unsigned total_checks = 0U;
    unsigned failed_checks = 0U;
    unsigned passed_cases = 0U;
    unsigned i;

    for (i = 0U; i < (unsigned)(sizeof(k_cases) / sizeof(k_cases[0])); i++) {
        const Td2InputMutationCase* test_case = &k_cases[i];
        Td2Runtime runtime;
        Td2RuntimeConfig config;
        char error[256];
        unsigned case_failed_checks = failed_checks;

        memset(&config, 0, sizeof(config));
        config.scene_dir = test_case->scene_dir;
        config.headless = true;
        config.scheduler_profile = test_case->profile;
        config.input_script = test_case->input_script;

        if (!td2_runtime_init(&runtime, &config, error, sizeof(error))) {
            fprintf(stderr, "FAIL %s runtime init: %s\n", test_case->label, error);
            return 1;
        }

        runtime.frame_counter = test_case->frame - runtime.design_pack.frame_number;
        if (!td2_runtime_sync_frame_state(&runtime, error, sizeof(error))) {
            fprintf(stderr, "FAIL %s sync error: %s\n", test_case->label, error);
            td2_runtime_free(&runtime);
            return 1;
        }

        expect_u16(test_case->label,
                   "state_0960",
                   runtime.state.has_state_0960,
                   runtime.state.state_0960,
                   test_case->expect_state_0960,
                   test_case->expected_state_0960,
                   &total_checks,
                   &failed_checks);
        expect_u16(test_case->label,
                   "state_1c70",
                   runtime.state.has_state_1c70,
                   runtime.state.state_1c70,
                   test_case->expect_state_1c70,
                   test_case->expected_state_1c70,
                   &total_checks,
                   &failed_checks);
        expect_u16(test_case->label,
                   "state_1c76",
                   runtime.state.has_state_1c76,
                   runtime.state.state_1c76,
                   test_case->expect_state_1c76,
                   test_case->expected_state_1c76,
                   &total_checks,
                   &failed_checks);
        expect_u16(test_case->label,
                   "state_09a2",
                   runtime.state.has_state_09a2,
                   runtime.state.state_09a2,
                   test_case->expect_state_09a2,
                   test_case->expected_state_09a2,
                   &total_checks,
                   &failed_checks);
        expect_u16(test_case->label,
                   "state_09a8",
                   runtime.state.has_state_09a8,
                   runtime.state.state_09a8,
                   test_case->expect_state_09a8,
                   test_case->expected_state_09a8,
                   &total_checks,
                   &failed_checks);
        expect_u16(test_case->label,
                   "state_137c",
                   runtime.state.has_state_137c,
                   runtime.state.state_137c,
                   test_case->expect_state_137c,
                   test_case->expected_state_137c,
                   &total_checks,
                   &failed_checks);
        expect_u16(test_case->label,
                   "dp_0020",
                   runtime.state.has_dp_0020,
                   runtime.state.dp_0020,
                   test_case->expect_dp_0020,
                   test_case->expected_dp_0020,
                   &total_checks,
                   &failed_checks);
        expect_u16(test_case->label,
                   "dp_0022",
                   runtime.state.has_dp_0022,
                   runtime.state.dp_0022,
                   test_case->expect_dp_0022,
                   test_case->expected_dp_0022,
                   &total_checks,
                   &failed_checks);
        expect_u16(test_case->label,
                   "dp_0053",
                   runtime.state.has_dp_0053,
                   runtime.state.dp_0053,
                   test_case->expect_dp_0053,
                   test_case->expected_dp_0053,
                   &total_checks,
                   &failed_checks);
        expect_u16(test_case->label,
                   "dp_0054",
                   runtime.state.has_dp_0054,
                   runtime.state.dp_0054,
                   test_case->expect_dp_0054,
                   test_case->expected_dp_0054,
                   &total_checks,
                   &failed_checks);

        td2_runtime_free(&runtime);
        if (failed_checks == case_failed_checks) {
            passed_cases++;
        }
    }

    if (failed_checks != 0U) {
        fprintf(stderr,
                "FAIL: input mutation smoke mismatched %u checks across %u/%zu cases\n",
                failed_checks,
                passed_cases,
                sizeof(k_cases) / sizeof(k_cases[0]));
        return 1;
    }

    printf("PASS: input mutation smoke matched %u checks across %u cases\n",
           total_checks,
           passed_cases);
    return 0;
}
